### PR TITLE
Test for 3.7 and update descriptions

### PR DESCRIPTION
**Pull request by tonybaloney**

### CODE REVIEW

**Comment by rob-smallshire** [comment]
It's probably time to drop support for 3.3 and likely 3.4 as well.

**Comment by tonybaloney** [comment]
Was about to suggest dropping 3.3 as it's causing the build to fail because it's no longer supported in the test distro.

**Comment by tonybaloney** [comment]
3.4 is still supported and stable

**Comment by tonybaloney** [comment]
Should work now! Sorry for all the commits (doing this in the UI)

**Pull request merged**
